name: CI/CD - Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build, Lint and Test
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout código
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # 3. Instalar dependências
      - name: Install dependencies
        run: npm ci

      # 4. Rodar lint (opcional)
      - name: Run lint
        run: npm run lint --if-present

      # 5. Rodar testes (opcional)
      - name: Run tests
        run: npm test --if-present

      # 6. Fazer build do projeto
      - name: Build project
        run: npm run build

      # 7. Upload de artefato de build (para deploy posterior)
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # 1. Baixar artefato gerado no job anterior
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./dist

      # 2. Publicar no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com

  preview:
    name: Deploy Preview for PRs
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout código
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # 3. Instalar e buildar
      - name: Install and Build
        run: |
          npm ci
          npm run build

      # 4. Upload de preview (mantido por 30 dias)
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v2
        with:
          source-dir: ./dist
          preview-branch: gh-pages
          github-token: ${{ secrets.GITHUB_TOKEN }}
